# 開発用: ベースはPHP-FPM
FROM php:8.3-fpm

# 必要なシステムパッケージとPHP拡張をインストール
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libonig-dev \
    libpng-dev \
    libjpeg-dev \
    curl \
    nano \
    # xdebugインストールに必要な依存関係
    # $PHPIZE_DEPS \
    && rm -rf /var/lib/apt/lists/* \
    # PHP拡張のインストール
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath zip gd \
    # Composerのインストール
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    # Xdebugのインストールと有効化
    # && pecl install xdebug \
    # && docker-php-ext-enable xdebug

# Xdebugの設定 (開発環境ではホストのIPに接続させる)
# COPY ./docker/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# 作業ディレクトリ
WORKDIR /var/www/html

# COPY ./backend/composer.json ./backend/composer.lock ./
COPY ../composer.json ../composer.lock ../ ./

RUN php -d memory_limit=-1 /usr/local/bin/composer install --prefer-dist --no-interaction
